/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services Route */
        get: operations["list_services_route_services_get"];
        put?: never;
        /** Create Service Route */
        post: operations["create_service_route_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Patients Route */
        get: operations["list_patients_route_patients_get"];
        put?: never;
        /** Create Patient Route */
        post: operations["create_patient_route_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient Route */
        get: operations["get_patient_route_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Visits Route */
        get: operations["list_visits_route_visits_get"];
        put?: never;
        /** Create Visit Route */
        post: operations["create_visit_route_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Visit Route */
        get: operations["get_visit_route_visits__visit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Visit Executions Route */
        get: operations["list_visit_executions_route_visits__visit_id__executions_get"];
        put?: never;
        /** Create Service Execution Route */
        post: operations["create_service_execution_route_visits__visit_id__executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads Route */
        get: operations["list_leads_route_leads_get"];
        put?: never;
        /** Create Lead Route */
        post: operations["create_lead_route_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Route */
        get: operations["get_lead_route_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products Route */
        get: operations["list_products_route_products_get"];
        put?: never;
        /** Create Product Route */
        post: operations["create_product_route_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product Route */
        get: operations["get_product_route_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{execution_id}/consumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Service Consumptions Route */
        get: operations["list_service_consumptions_route_executions__execution_id__consumptions_get"];
        put?: never;
        /** Create Service Consumption Route */
        post: operations["create_service_consumption_route_executions__execution_id__consumptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{execution_id}/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Charge Route */
        post: operations["create_charge_route_executions__execution_id__charges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Charges Route */
        get: operations["list_charges_route_charges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{charge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Charge Route */
        get: operations["get_charge_route_charges__charge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{charge_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payments Route */
        get: operations["list_payments_route_charges__charge_id__payments_get"];
        put?: never;
        /** Create Payment Route */
        post: operations["create_payment_route_charges__charge_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Entry Route */
        post: operations["register_entry_route_products__product_id__entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Adjustment Route */
        post: operations["register_adjustment_route_products__product_id__adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Transfer Route */
        post: operations["register_transfer_route_products__product_id__transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movements Route */
        get: operations["list_movements_route_products__product_id__movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Balance Route */
        get: operations["get_balance_route_products__product_id__balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations Route */
        get: operations["list_locations_route_locations_get"];
        put?: never;
        /** Create Location Route */
        post: operations["create_location_route_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practitioners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Practitioner Route */
        post: operations["create_practitioner_route_practitioners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Capability Route */
        post: operations["create_capability_route_capabilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practitioners/eligible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eligible Practitioners Route */
        get: operations["list_eligible_practitioners_route_practitioners_eligible_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Availability Rule Route */
        post: operations["create_availability_rule_route_availability_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Schedule Block Route */
        post: operations["create_schedule_block_route_schedule_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Slots Route */
        post: operations["query_slots_route_slots_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Appointments Route
         * @description Agenda read: the acting organization's appointments, half-open window.
         *
         *     The window is ``[from_date, to_date)``; both bounds are optional and
         *     passed as RFC 3339 instants. Location/practitioner filters narrow the
         *     result; the tenant always comes from the context, never from a query
         *     parameter (X3).
         */
        get: operations["list_appointments_route_appointments_get"];
        put?: never;
        /** Create Appointment Route */
        post: operations["create_appointment_route_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appointment Route */
        get: operations["get_appointment_route_appointments__appointment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Appointment Route */
        post: operations["cancel_appointment_route_appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedule Appointment Route */
        post: operations["reschedule_appointment_route_appointments__appointment_id__reschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdjustmentCreate
         * @description A reason-required correction at one location (a movement row, always).
         */
        AdjustmentCreate: {
            /** Location Id */
            location_id: number;
            /** Quantity */
            quantity: number | string;
            /** Reason */
            reason: string;
        };
        /**
         * AppointmentCancel
         * @description Empty by design: the appointment is identified by the path, and nothing
         *     about the cancellation is caller-supplied. ``extra='forbid'`` keeps a
         *     client from smuggling state through the body.
         */
        AppointmentCancel: Record<string, never>;
        /** AppointmentCreate */
        AppointmentCreate: {
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /**
         * AppointmentListItem
         * @description Agenda read DTO: the appointment plus the names the agenda renders.
         *
         *     The names are joined at the application boundary (relationships), so the
         *     frontend never needs per-row lookups and never sees raw mockData shapes.
         */
        AppointmentListItem: {
            /** Id */
            id: number;
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** State */
            state: string;
            /** Lead Name */
            lead_name: string;
            /** Service Name */
            service_name: string;
            /** Practitioner Name */
            practitioner_name: string;
            /** Location Name */
            location_name: string;
        };
        /** AppointmentRead */
        AppointmentRead: {
            /** Id */
            id: number;
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** State */
            state: string;
        };
        /** AppointmentReschedule */
        AppointmentReschedule: {
            /**
             * New Start
             * Format: date-time
             */
            new_start: string;
        };
        /** AvailabilityRuleCreate */
        AvailabilityRuleCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Local
             * Format: time
             */
            start_local: string;
            /**
             * End Local
             * Format: time
             */
            end_local: string;
        };
        /** AvailabilityRuleRead */
        AvailabilityRuleRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Local
             * Format: time
             */
            start_local: string;
            /**
             * End Local
             * Format: time
             */
            end_local: string;
        };
        /** BalanceRead */
        BalanceRead: {
            /** Product Id */
            product_id: number;
            /** Location Id */
            location_id: number;
            /** Available */
            available: string;
        };
        /** CapabilityCreate */
        CapabilityCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** CapabilityRead */
        CapabilityRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** ChargeCreate */
        ChargeCreate: {
            /** Amount */
            amount?: number | string | null;
        };
        /** ChargeRead */
        ChargeRead: {
            /** Id */
            id: number;
            /** Service Execution Id */
            service_execution_id: number;
            /** Amount */
            amount: string;
            /** Paid */
            paid: string;
            /** Outstanding */
            outstanding: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EntryCreate
         * @description A purchase/initial stock input, targeted at one location.
         */
        EntryCreate: {
            /** Location Id */
            location_id: number;
            /** Quantity */
            quantity: number | string;
            /** Unit Price */
            unit_price?: number | string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadCreate */
        LeadCreate: {
            /** Full Name */
            full_name: string;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /**
             * Acquisition Source
             * @enum {string}
             */
            acquisition_source: "promotion" | "referral" | "direct";
            /** Service Need Id */
            service_need_id?: number | null;
        };
        /** LeadRead */
        LeadRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Contact Phone */
            contact_phone: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Acquisition Source */
            acquisition_source: string;
            /** Service Need Id */
            service_need_id: number | null;
            /** Commercial Status */
            commercial_status: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** LocationRead */
        LocationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Is Active */
            is_active: boolean;
        };
        /** MovementRead */
        MovementRead: {
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Location Id */
            location_id: number;
            /** Type */
            type: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string | null;
            /** Reason */
            reason: string | null;
            /** Id Consumo Origen */
            id_consumo_origen: number | null;
            /** Transfer Id */
            transfer_id: string | null;
            /**
             * Moved At
             * Format: date-time
             */
            moved_at: string;
        };
        /** PatientCreate */
        PatientCreate: {
            /** Full Name */
            full_name: string;
            /** Dni */
            dni?: string | null;
            /** Sexo */
            sexo?: ("M" | "F" | "O") | null;
            /** Phone */
            phone?: string | null;
            /** Birth Date */
            birth_date?: string | null;
        };
        /** PatientRead */
        PatientRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Dni */
            dni: string | null;
            /** Sexo */
            sexo: string | null;
            /** Phone */
            phone: string | null;
            /** Birth Date */
            birth_date: string | null;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Amount */
            amount: number | string;
            /** Method */
            method: string;
        };
        /** PaymentRead */
        PaymentRead: {
            /** Id */
            id: number;
            /** Charge Id */
            charge_id: number;
            /** Amount */
            amount: string;
            /** Method */
            method: string;
            /**
             * Paid At
             * Format: date-time
             */
            paid_at: string;
        };
        /** PractitionerCreate */
        PractitionerCreate: {
            /** Display Name */
            display_name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** PractitionerRead */
        PractitionerRead: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "consumible" | "reventa";
        };
        /** ProductRead */
        ProductRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Kind */
            kind: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ScheduleBlockCreate */
        ScheduleBlockCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
        };
        /** ScheduleBlockRead */
        ScheduleBlockRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
        };
        /** ServiceConsumptionCreate */
        ServiceConsumptionCreate: {
            /** Product Id */
            product_id: number;
            /** Quantity */
            quantity: number | string;
            /** Unit Price */
            unit_price: number | string;
        };
        /** ServiceConsumptionRead */
        ServiceConsumptionRead: {
            /** Id */
            id: number;
            /** Service Execution Id */
            service_execution_id: number;
            /** Product Id */
            product_id: number;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: string;
            /** Unit Price */
            unit_price: string;
            /** Amount */
            amount: string;
            /**
             * Consumed At
             * Format: date-time
             */
            consumed_at: string;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ServiceExecutionCreate */
        ServiceExecutionCreate: {
            /** Service Id */
            service_id: number;
            /** Executed Price */
            executed_price: number | string;
        };
        /** ServiceExecutionRead */
        ServiceExecutionRead: {
            /** Id */
            id: number;
            /** Visit Id */
            visit_id: number;
            /** Service Id */
            service_id: number;
            /** Service Name */
            service_name: string;
            /** Executed Price */
            executed_price: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
        };
        /** ServiceRead */
        ServiceRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Is Active */
            is_active: boolean;
        };
        /** SlotQuery */
        SlotQuery: {
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
        };
        /** SlotResult */
        SlotResult: {
            /** Practitioner Id */
            practitioner_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /**
         * TransferCreate
         * @description Move stock between two locations of the same organization.
         */
        TransferCreate: {
            /** Origin Location Id */
            origin_location_id: number;
            /** Destination Location Id */
            destination_location_id: number;
            /** Quantity */
            quantity: number | string;
            /** Reason */
            reason?: string | null;
        };
        /** TransferRead */
        TransferRead: {
            /** Transfer Id */
            transfer_id: string;
            /** Product Id */
            product_id: number;
            /** Origin Location Id */
            origin_location_id: number;
            /** Destination Location Id */
            destination_location_id: number;
            /** Quantity */
            quantity: string;
            /** Reason */
            reason: string | null;
            /** Out Movement Id */
            out_movement_id: number;
            /** In Movement Id */
            in_movement_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VisitCreate */
        VisitCreate: {
            /** Patient Id */
            patient_id: number;
            /** Appointment Id */
            appointment_id?: number | null;
            /** Practitioner Id */
            practitioner_id?: number | null;
            /** Location Id */
            location_id?: number | null;
        };
        /** VisitDetailRead */
        VisitDetailRead: {
            /** Id */
            id: number;
            /** Patient Id */
            patient_id: number;
            /** Patient Name */
            patient_name: string;
            /** Appointment Id */
            appointment_id: number | null;
            /** Practitioner Id */
            practitioner_id: number;
            /** Practitioner Name */
            practitioner_name: string;
            /** Location Id */
            location_id: number;
            /** Location Name */
            location_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Executions */
            executions: components["schemas"]["ServiceExecutionRead"][];
        };
        /** VisitRead */
        VisitRead: {
            /** Id */
            id: number;
            /** Patient Id */
            patient_id: number;
            /** Patient Name */
            patient_name: string;
            /** Appointment Id */
            appointment_id: number | null;
            /** Practitioner Id */
            practitioner_id: number;
            /** Practitioner Name */
            practitioner_name: string;
            /** Location Id */
            location_id: number;
            /** Location Name */
            location_name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_services_route_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"][];
                };
            };
        };
    };
    create_service_route_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patients_route_patients_get: {
        parameters: {
            query?: {
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_route_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_route_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_visits_route_visits_get: {
        parameters: {
            query?: {
                patient_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_visit_route_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visit_route_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_visit_executions_route_visits__visit_id__executions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceExecutionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_execution_route_visits__visit_id__executions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceExecutionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceExecutionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_route_leads_get: {
        parameters: {
            query?: {
                search?: string | null;
                commercial_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_route_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_route_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_route_products_get: {
        parameters: {
            query?: {
                search?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_route_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_route_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_service_consumptions_route_executions__execution_id__consumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceConsumptionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_consumption_route_executions__execution_id__consumptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceConsumptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceConsumptionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_charge_route_executions__execution_id__charges_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChargeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_charges_route_charges_get: {
        parameters: {
            query?: {
                execution_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_charge_route_charges__charge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_route_charges__charge_id__payments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_payment_route_charges__charge_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charge_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_entry_route_products__product_id__entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_adjustment_route_products__product_id__adjustments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_transfer_route_products__product_id__transfers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movements_route_products__product_id__movements_get: {
        parameters: {
            query: {
                /** @description The location whose kardex is read. */
                location_id: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_balance_route_products__product_id__balance_get: {
        parameters: {
            query: {
                /** @description The location whose balance is read. */
                location_id: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_route_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
        };
    };
    create_location_route_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practitioner_route_practitioners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PractitionerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capability_route_capabilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eligible_practitioners_route_practitioners_eligible_get: {
        parameters: {
            query: {
                service_id: number;
                location_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_availability_rule_route_availability_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_block_route_schedule_blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleBlockRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_slots_route_slots_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_route_appointments_get: {
        parameters: {
            query?: {
                from_date?: string | null;
                to_date?: string | null;
                location_id?: number | null;
                practitioner_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment_route_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appointment_route_appointments__appointment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_appointment_route_appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AppointmentCancel"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reschedule_appointment_route_appointments__appointment_id__reschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentReschedule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
