/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services Route */
        get: operations["list_services_route_services_get"];
        put?: never;
        /** Create Service Route */
        post: operations["create_service_route_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads Route */
        get: operations["list_leads_route_leads_get"];
        put?: never;
        /** Create Lead Route */
        post: operations["create_lead_route_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Route */
        get: operations["get_lead_route_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations Route */
        get: operations["list_locations_route_locations_get"];
        put?: never;
        /** Create Location Route */
        post: operations["create_location_route_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practitioners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Practitioner Route */
        post: operations["create_practitioner_route_practitioners_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Capability Route */
        post: operations["create_capability_route_capabilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practitioners/eligible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eligible Practitioners Route */
        get: operations["list_eligible_practitioners_route_practitioners_eligible_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Availability Rule Route */
        post: operations["create_availability_rule_route_availability_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Schedule Block Route */
        post: operations["create_schedule_block_route_schedule_blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Slots Route */
        post: operations["query_slots_route_slots_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Appointments Route
         * @description Agenda read: the acting organization's appointments, half-open window.
         *
         *     The window is ``[from_date, to_date)``; both bounds are optional and
         *     passed as RFC 3339 instants. Location/practitioner filters narrow the
         *     result; the tenant always comes from the context, never from a query
         *     parameter (X3).
         */
        get: operations["list_appointments_route_appointments_get"];
        put?: never;
        /** Create Appointment Route */
        post: operations["create_appointment_route_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Appointment Route */
        get: operations["get_appointment_route_appointments__appointment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Appointment Route */
        post: operations["cancel_appointment_route_appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointments/{appointment_id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reschedule Appointment Route */
        post: operations["reschedule_appointment_route_appointments__appointment_id__reschedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppointmentCancel
         * @description Empty by design: the appointment is identified by the path, and nothing
         *     about the cancellation is caller-supplied. ``extra='forbid'`` keeps a
         *     client from smuggling state through the body.
         */
        AppointmentCancel: Record<string, never>;
        /** AppointmentCreate */
        AppointmentCreate: {
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /**
         * AppointmentListItem
         * @description Agenda read DTO: the appointment plus the names the agenda renders.
         *
         *     The names are joined at the application boundary (relationships), so the
         *     frontend never needs per-row lookups and never sees raw mockData shapes.
         */
        AppointmentListItem: {
            /** Id */
            id: number;
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** State */
            state: string;
            /** Lead Name */
            lead_name: string;
            /** Service Name */
            service_name: string;
            /** Practitioner Name */
            practitioner_name: string;
            /** Location Name */
            location_name: string;
        };
        /** AppointmentRead */
        AppointmentRead: {
            /** Id */
            id: number;
            /** Lead Id */
            lead_id: number;
            /** Service Id */
            service_id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
            /** State */
            state: string;
        };
        /** AppointmentReschedule */
        AppointmentReschedule: {
            /**
             * New Start
             * Format: date-time
             */
            new_start: string;
        };
        /** AvailabilityRuleCreate */
        AvailabilityRuleCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Local
             * Format: time
             */
            start_local: string;
            /**
             * End Local
             * Format: time
             */
            end_local: string;
        };
        /** AvailabilityRuleRead */
        AvailabilityRuleRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /** Day Of Week */
            day_of_week: number;
            /**
             * Start Local
             * Format: time
             */
            start_local: string;
            /**
             * End Local
             * Format: time
             */
            end_local: string;
        };
        /** CapabilityCreate */
        CapabilityCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** CapabilityRead */
        CapabilityRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeadCreate */
        LeadCreate: {
            /** Full Name */
            full_name: string;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /**
             * Acquisition Source
             * @enum {string}
             */
            acquisition_source: "promotion" | "referral" | "direct";
            /** Service Need Id */
            service_need_id?: number | null;
        };
        /** LeadRead */
        LeadRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Contact Phone */
            contact_phone: string | null;
            /** Contact Email */
            contact_email: string | null;
            /** Acquisition Source */
            acquisition_source: string;
            /** Service Need Id */
            service_need_id: number | null;
            /** Commercial Status */
            commercial_status: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** LocationRead */
        LocationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Is Active */
            is_active: boolean;
        };
        /** PractitionerCreate */
        PractitionerCreate: {
            /** Display Name */
            display_name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** PractitionerRead */
        PractitionerRead: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ScheduleBlockCreate */
        ScheduleBlockCreate: {
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
        };
        /** ScheduleBlockRead */
        ScheduleBlockRead: {
            /** Id */
            id: number;
            /** Practitioner Id */
            practitioner_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Start Utc
             * Format: date-time
             */
            start_utc: string;
            /**
             * End Utc
             * Format: date-time
             */
            end_utc: string;
        };
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ServiceRead */
        ServiceRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Is Active */
            is_active: boolean;
        };
        /** SlotQuery */
        SlotQuery: {
            /** Service Id */
            service_id: number;
            /** Location Id */
            location_id: number;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
        };
        /** SlotResult */
        SlotResult: {
            /** Practitioner Id */
            practitioner_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_services_route_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"][];
                };
            };
        };
    };
    create_service_route_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_route_leads_get: {
        parameters: {
            query?: {
                search?: string | null;
                commercial_status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_route_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_route_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_route_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
        };
    };
    create_location_route_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_practitioner_route_practitioners_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PractitionerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capability_route_capabilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapabilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eligible_practitioners_route_practitioners_eligible_get: {
        parameters: {
            query: {
                service_id: number;
                location_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_availability_rule_route_availability_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_block_route_schedule_blocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBlockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleBlockRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_slots_route_slots_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_route_appointments_get: {
        parameters: {
            query?: {
                from_date?: string | null;
                to_date?: string | null;
                location_id?: number | null;
                practitioner_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment_route_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appointment_route_appointments__appointment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_appointment_route_appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AppointmentCancel"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reschedule_appointment_route_appointments__appointment_id__reschedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentReschedule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
