export const inboxHtml = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>Odonto Smart - Simulacion end-to-end</title>
<style>
:root{font-family:Inter,system-ui;color:#152536;background:#eef3f7}*{box-sizing:border-box}body{margin:0}header{background:#123b52;color:#fff;padding:22px 5vw;position:sticky;top:0;z-index:2}header h1{margin:0 0 6px;font-size:23px}main{max-width:1200px;margin:auto;padding:24px}.toolbar,.panel,.card,.metric{background:#fff;border:1px solid #d8e2e9;border-radius:12px;padding:16px}.toolbar{margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:14px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px}.metric strong{display:block;font-size:28px;color:#086788}.metric span,.muted{font-size:13px;color:#617382}button,input,select{border:1px solid #aebdc7;border-radius:7px;padding:8px;margin:3px}button{background:#086788;color:#fff;cursor:pointer}button.secondary{background:#fff;color:#086788}button.danger{background:#a63838}h2{margin-top:32px;border-bottom:1px solid #cedbe3;padding-bottom:8px}.tag{display:inline-block;background:#e5f2f6;border-radius:6px;padding:3px 7px;font-size:12px;margin:5px 0}.form-row{display:flex;flex-wrap:wrap;align-items:center}.form-row>*{min-width:150px;flex:1}pre{white-space:pre-wrap}.empty{color:#72818d;padding:14px}.status-list{display:flex;gap:12px;flex-wrap:wrap}.status-list span{background:#f2f6f8;padding:8px;border-radius:7px}
</style></head><body>
<header><h1>Odonto Smart - Demo 100% simulada</h1><div id="time"></div></header><main>
<section class="toolbar"><strong>Vista 5 - Reloj de simulacion</strong><div>
<button onclick="advance(5,'minutes')">+5 minutos</button><button onclick="advance(1,'hours')">+1 hora</button><button onclick="advance(1,'days')">+1 dia</button>
<input id="goto-time" type="datetime-local"><button onclick="goToTime()">Ir a fecha/hora</button><button class="secondary" onclick="runScheduler()">Ejecutar reglas</button><button onclick="runDemo()">Ejecutar demo Ana</button>
</div></section>
<h2>Metricas de simulacion</h2><div id="metrics" class="metrics"></div>
<h2>Vista 1 - Agenda simulada</h2><section class="panel"><form id="create-form" class="form-row"><select id="patient" required></select><select id="branch" required></select><select id="doctor" required></select><input id="start" type="datetime-local" required><input id="end" type="datetime-local" required><input id="title" value="Cita ficticia" required><button>Crear cita</button></form></section><div id="appointments" class="grid"></div>
<h2>Vista 2 - Seguimiento</h2><div id="tracking" class="grid"></div><h3>Cierre del dia: citas de manana</h3><div id="closing" class="status-list"></div><h3>Tareas para recepcion</h3><div id="tasks" class="grid"></div>
<h2>Vista 3 - WhatsApp simulado</h2><div id="messages" class="grid"></div>
<h2>Vista 4 - Llamadas simuladas</h2><div id="calls" class="grid"></div>
</main><script>
const actions=['CONFIRM','REQUEST_RESCHEDULE','CANCEL','NO_RESPONSE'];
const callResults=['ANSWERED_CONFIRMED','ANSWERED_CANCELLED','ANSWERED_RESCHEDULE','NO_ANSWER','WRONG_NUMBER','PENDING'];
let state;
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok){alert(x.error);throw new Error(x.error)}return x}
async function refresh(data){state=data||await api('/api/state');document.querySelector('#time').textContent='Hora virtual: '+fmt(state.simulationTime);renderMetrics();renderCatalogs();renderAppointments();renderTracking();renderClosing();renderTasks();renderMessages();renderCalls()}
function renderMetrics(){const labels={scheduled:'Programadas',confirmed:'Confirmadas',pending:'Pendientes',cancelled:'Canceladas',rescheduleRequested:'Reprogramacion',noResponse:'Sin respuesta',simulatedWhatsApps:'WhatsApps',simulatedCalls:'Llamadas'};document.querySelector('#metrics').innerHTML=Object.entries(labels).map(([k,v])=>'<div class="metric"><strong>'+state.metrics[k]+'</strong><span>'+v+'</span></div>').join('')}
function renderCatalogs(){fill('patient',state.catalogs.patients,x=>x.name+' - '+x.phone);fill('branch',state.catalogs.branches,x=>x.name);fill('doctor',state.catalogs.doctors,x=>x.name)}function fill(id,items,label){const el=document.querySelector('#'+id),old=el.value;el.innerHTML=items.map(x=>'<option value="'+x.id+'">'+esc(label(x))+'</option>').join('');if(old)el.value=old}
function renderAppointments(){render('appointments',state.appointments,a=>card(a.patientName,a.appointmentStatus+' / '+a.followupStatus,'<div>'+fmt(a.startsAt)+' - '+fmt(a.endsAt)+'</div><div>'+esc(a.branchName)+'</div><button onclick="editAppointment(\\''+a.id+'\\')">Editar</button><button class="danger" onclick="cancelAppointment(\\''+a.id+'\\')">Cancelar</button>'))}
function renderTracking(){render('tracking',state.tracking,r=>card(r.appointment.patientName,r.appointment.appointmentStatus+' / '+r.appointment.followupStatus,'Intentos: '+r.attemptCount+'<br>Ultimo: '+contact(r.lastContact)+'<br>Proximo: '+contact(r.nextContact)))}
function renderClosing(){const s=state.closingSummary;document.querySelector('#closing').innerHTML='<span>Fecha: '+s.date+'</span><span>Confirmadas: '+s.confirmed.length+'</span><span>Pendientes: '+s.pending.length+'</span><span>Canceladas: '+s.cancelled.length+'</span><span>Reprogramar: '+s.rescheduleRequested.length+'</span><span>Sin respuesta: '+s.noResponse.length+'</span>'}
function renderTasks(){render('tasks',state.tasks,t=>card('Tarea de recepcion',t.status,esc(t.description)+'<br>'+fmt(t.createdAt)))}
function renderMessages(){render('messages',state.messages,m=>card(m.patientName,m.attemptType+' / '+m.status,'A: '+esc(m.recipientPhone)+' - '+fmt(m.sentAt)+'<pre>'+esc(m.text)+'</pre>Respuesta: '+(m.response||'pendiente')+'<br>'+actions.map(x=>'<button onclick="reply(\\''+m.id+'\\',\\''+x+'\\')">'+x+'</button>').join('')))}
function renderCalls(){render('calls',state.calls,c=>card(c.patientName,c.attemptType,'Hora: '+fmt(c.attemptedAt)+'<br>Resultado: '+c.result+'<br><select onchange="callResult(\\''+c.id+'\\',this.value)"><option>Elegir resultado</option>'+callResults.map(x=>'<option>'+x+'</option>').join('')+'</select>'))}
function render(id,items,fn){document.querySelector('#'+id).innerHTML=items.length?items.map(fn).join(''):'<div class="empty">Sin registros</div>'}function card(title,tag,body){return '<article class="card"><strong>'+esc(title)+'</strong><br><span class="tag">'+esc(tag)+'</span><div class="muted">'+body+'</div></article>'}function fmt(d){return new Date(d).toLocaleString('es-PE',{timeZone:'America/Lima'})}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function contact(c){return c?c.attemptType+' - '+fmt(c.at):'Ninguno'}
async function advance(value,unit){const b={};b[unit]=value;refresh(await api('/api/clock','POST',b))}async function goToTime(){const v=document.querySelector('#goto-time').value;if(v)refresh(await api('/api/clock','POST',{time:new Date(v).toISOString()}))}async function runScheduler(){refresh(await api('/api/scheduler/run','POST',{}))}async function runDemo(){refresh(await api('/api/demo/run','POST',{}))}async function reply(id,action){refresh(await api('/api/messages/'+id+'/response','POST',{action}))}async function callResult(id,result){if(result==='Elegir resultado')return;refresh(await api('/api/calls/'+id+'/result','POST',{result}))}
async function cancelAppointment(id){const reason=prompt('Motivo ficticio de cancelacion:','Cancelacion manual simulada');if(reason)refresh(await api('/api/appointments/'+id+'/cancel','POST',{reason}))}async function editAppointment(id){const a=state.appointments.find(x=>x.id===id),start=prompt('Nueva fecha inicio ISO:',a.startsAt),end=prompt('Nueva fecha fin ISO:',a.endsAt);if(start&&end)refresh(await api('/api/appointments/'+id,'PUT',{startsAt:start,endsAt:end}))}
document.querySelector('#create-form').addEventListener('submit',async e=>{e.preventDefault();refresh(await api('/api/appointments','POST',{patientId:document.querySelector('#patient').value,branchId:document.querySelector('#branch').value,doctorId:document.querySelector('#doctor').value,title:document.querySelector('#title').value,startsAt:new Date(document.querySelector('#start').value).toISOString(),endsAt:new Date(document.querySelector('#end').value).toISOString()}))});refresh();
</script></body></html>`;
